### ISSUE TITLE
Why not kubectx?

### ISSUE THREAD

**Issue by ahmetb** [postfinance/kubectl-ctx#2]
Hi, as the author of a more widely accepted tool 
https://github.com/ahmetb/kubectx, I am curious what this repo is hoping to achieve.

I’d love to work together and make a plugin out of a more established solution instead of duplicating efforts. There has been many clones of kubectx and they are not growing for a good reason.

**Comment by ghouscht** [comment]
Hi, I knew kubectx before and also used it previously to writing this plugin (thank you for your work!). This project started as a litte experiment to try out the new [kubectl plugin mechanism](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) and worked so well we decided to open source it.

In my opinion, the main benefit of this plugin is portability. It compiles down to a single statically linked binary with no additional runtime dependencies which in turn allows me to use it across different OS'es, windows/linux in my case.

**Comment by djboris9** [comment]
Ref: https://github.com/GoogleContainerTools/krew-index/pull/38
@ghouscht We should add a hint to the readme why this non-bash version exists

**Comment by zbindenren** [comment]
Or change name, maybe? kube-context?

**Comment by ahmetb** [comment]
I'm open to have a discussion about porting kubectx to Go. This came up a few times before too, this is good validation. I'll open an issue about it on the kubectx repo.

> maybe? kube-context?

kube-* prefix is [explicitly discouraged](https://github.com/GoogleContainerTools/krew/blob/master/docs/NAMING_GUIDE.md) for plugins.

**Comment by zbindenren** [comment]
Sorry, I meant `kubectl-context`. From the doc: A plugin is nothing more than a standalone executable file, whose name begins with `kubectl-`  (https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/)

Krew documentation is a little bit out of date. As of 1.12 you can now run the plugin with: 

`kubectl context`

instead of:

`kubectl plugin kubectl-context`

Personally I also use your plugin because of fzf integration and I am a Linux user. But I understand the Windows users without a shell.

**Comment by ahmetb** [comment]
I have opened https://github.com/ahmetb/kubectx/issues/115 that proposes rewriting kubectx in Go.

Way too many kubectx clones have been created to solve this problem in other languages. I think we should have proper windows support, and defragment the ecosystem.

P.S. krew docs shouldnt be out of date, can you please open an issue?

**Comment by zbindenren** [comment]
@ahmetb you rewrote it in go: https://github.com/ahmetb/kubectx/issues/115#issuecomment-621469413 so we are probably archiving this projects and create a link to your project.

**Comment by zbindenren** [comment]
Project is archived now.
